
services:
  kriolpos-db:
    #image: mysql:8.4 #LTS (29 May 2029)
    image: mariadb:11.4 #LTS (29 May 2029)
    dns:
      - 8.8.8.8
    ports:
      - "3306:3306"
    volumes:
      - ./.dbase:/var/lib/mysql:cached
    environment:
      - MARIADB_ROOT_PASSWORD=docker
      - MARIADB_DATABASE=kriolospos
      - MARIADB_USER=kriolospos
      - MARIADB_PASSWORD=kriolospos
      - TZ=Europe/Lisbon